services:
  - type: web
    name: codiss-cartographie
    runtime: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: uvicorn main_local:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
# Build forcé Mon Jun 29 23:49:36 UTC 2026
